name: Lint

on: [push, pull_request]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Black
        uses: psf/black@stable
